apiVersion: v1
kind: List
metadata:
  name: data-corban-navigator-deployment
items:

# Namespace
- apiVersion: v1
  kind: Namespace
  metadata:
    name: data-corban-navigator
    labels:
      app: data-corban-navigator

# Frontend Deployment
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: data-corban-frontend
    namespace: data-corban-navigator
    labels:
      app: data-corban-navigator
      component: frontend
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: data-corban-navigator
        component: frontend
    template:
      metadata:
        labels:
          app: data-corban-navigator
          component: frontend
      spec:
        containers:
        - name: frontend
          image: quay.io/seu-usuario/data-corban-frontend:latest
          ports:
          - containerPort: 80
            name: http
          env:
          - name: VITE_SUPABASE_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: SUPABASE_URL
          - name: VITE_SUPABASE_ANON_KEY
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: SUPABASE_KEY
          - name: VITE_API_URL
            value: "https://data-corban-sql-backend-data-corban-navigator.apps.seu-cluster.com"
          - name: VITE_POSTGRES_API_URL
            value: "https://data-corban-postgres-backend-data-corban-navigator.apps.seu-cluster.com"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3

# SQL Backend Deployment
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: data-corban-sql-backend
    namespace: data-corban-navigator
    labels:
      app: data-corban-navigator
      component: sql-backend
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: data-corban-navigator
        component: sql-backend
    template:
      metadata:
        labels:
          app: data-corban-navigator
          component: sql-backend
      spec:
        containers:
        - name: sql-backend
          image: quay.io/seu-usuario/data-corban-sql-backend:latest
          ports:
          - containerPort: 3001
            name: api
          env:
          - name: PORT
            value: "3001"
          - name: NODE_ENV
            value: "production"
          - name: SQLSERVER_HOST
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: SQLSERVER_HOST
          - name: SQLSERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: SQLSERVER_PORT
          - name: SQLSERVER_USER
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: SQLSERVER_USER
          - name: SQLSERVER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: SQLSERVER_PASSWORD
          - name: SQLSERVER_DB
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: SQLSERVER_DB
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3

# PostgreSQL Backend Deployment
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: data-corban-postgres-backend
    namespace: data-corban-navigator
    labels:
      app: data-corban-navigator
      component: postgres-backend
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: data-corban-navigator
        component: postgres-backend
    template:
      metadata:
        labels:
          app: data-corban-navigator
          component: postgres-backend
      spec:
        containers:
        - name: postgres-backend
          image: quay.io/seu-usuario/data-corban-postgres-backend:latest
          ports:
          - containerPort: 3002
            name: api
          env:
          - name: NODE_ENV
            value: "production"
          - name: HOST
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: POSTGRES_HOST
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: POSTGRES_PORT
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: POSTGRES_USER
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: POSTGRES_PASSWORD
          - name: DB
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: POSTGRES_DB
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3

# Services
- apiVersion: v1
  kind: Service
  metadata:
    name: data-corban-frontend
    namespace: data-corban-navigator
    labels:
      app: data-corban-navigator
      component: frontend
  spec:
    selector:
      app: data-corban-navigator
      component: frontend
    ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP

- apiVersion: v1
  kind: Service
  metadata:
    name: data-corban-sql-backend
    namespace: data-corban-navigator
    labels:
      app: data-corban-navigator
      component: sql-backend
  spec:
    selector:
      app: data-corban-navigator
      component: sql-backend
    ports:
    - name: api
      port: 3001
      targetPort: 3001
      protocol: TCP

- apiVersion: v1
  kind: Service
  metadata:
    name: data-corban-postgres-backend
    namespace: data-corban-navigator
    labels:
      app: data-corban-navigator
      component: postgres-backend
  spec:
    selector:
      app: data-corban-navigator
      component: postgres-backend
    ports:
    - name: api
      port: 3002
      targetPort: 3002
      protocol: TCP

# Routes
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: data-corban-frontend
    namespace: data-corban-navigator
    labels:
      app: data-corban-navigator
      component: frontend
  spec:
    to:
      kind: Service
      name: data-corban-frontend
      weight: 100
    port:
      targetPort: http
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
    wildcardPolicy: None

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: data-corban-sql-backend
    namespace: data-corban-navigator
    labels:
      app: data-corban-navigator
      component: sql-backend
  spec:
    to:
      kind: Service
      name: data-corban-sql-backend
      weight: 100
    port:
      targetPort: api
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
    wildcardPolicy: None

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: data-corban-postgres-backend
    namespace: data-corban-navigator
    labels:
      app: data-corban-navigator
      component: postgres-backend
  spec:
    to:
      kind: Service
      name: data-corban-postgres-backend
      weight: 100
    port:
      targetPort: api
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
    wildcardPolicy: None
