apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: data-corban-network-policy
  namespace: data-corban-navigator
spec:
  podSelector:
    matchLabels:
      app: data-corban-navigator
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Permitir tráfego do router OpenShift
  - from:
    - namespaceSelector:
        matchLabels:
          name: openshift-ingress
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 3001
    - protocol: TCP
      port: 3002
  # Permitir comunicação entre componentes da aplicação
  - from:
    - podSelector:
        matchLabels:
          app: data-corban-navigator
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 3001
    - protocol: TCP
      port: 3002
  egress:
  # Permitir acesso a DNS
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Permitir acesso ao Supabase
  - to: []
    ports:
    - protocol: TCP
      port: 443
  # Permitir acesso aos bancos de dados externos
  - to: []
    ports:
    - protocol: TCP
      port: 1433  # SQL Server
    - protocol: TCP
      port: 5432  # PostgreSQL
    - protocol: TCP
      port: 49172 # SQL Server custom port

---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: data-corban-scc
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowedCapabilities: []
defaultAddCapabilities: []
fsGroup:
  type: RunAsAny
readOnlyRootFilesystem: false
requiredDropCapabilities:
- ALL
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- runtime/default
supplementalGroups:
  type: RunAsAny
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
